# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - doodleverse-prod

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          # npm i -g vite
          cd server
          npm i
          cd ../client
          npm i
          npm run build
          cd ..

          # npm ci
          # NODE_ENV=production npm run build
          # npm run start

          cd server
          node index.js
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          SESSION_SECRET: ${{secrets.SESSION_SECRET}}
          DB_CONNECTION_STRING: ${{secrets.DB_CONNECTION_STRING}}
          
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D101973C689F4DFE9942F7BBFB644F2B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_09672EE76B624161B022668EC2C14E7E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B566670C1F714BE5899A336155C7731E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'doodleverse-prod'
          slot-name: 'Production'
          package: .
          